# Generated by Django 3.1.6 on 2021-02-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tutor',
            new_name='teacher',
        ),
    ]
