# Generated by Django 3.1.6 on 2021-02-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nv', '0002_auto_20210214_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k1', models.IntegerField()),
                ('k2', models.IntegerField()),
                ('n1', models.IntegerField()),
                ('n2', models.IntegerField()),
                ('n3', models.IntegerField()),
                ('n4', models.IntegerField()),
                ('n5', models.IntegerField()),
                ('n6', models.IntegerField()),
                ('e', models.IntegerField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nv.course')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nv.student')),
            ],
        ),
    ]
